### ISSUE TITLE
Linking scores back to Dataset

### ISSUE THREAD

**Issue by felixkluge** [mad-lab-fau/tpcp#75]
I have defined a Dataset, Pipeline (with an algorithm) and a score function and can run the Pipeline on the complete Dataset using the tpcp.validate.Scorer .

What is an elegant way to link the individual datapoint scores back to the original Dataset (containing information such as participant_id)? 

I currently see two options:
- Using the index only, i.e., using the index of the Dataset to get the results in the returned single score list (using the same index)
- Adding Dataset information to the output of the score function

What would be the most elegant way?

**Comment by AKuederle** [comment]
I don't think there is any direct build-in method. Mainly, because the primary goal of the Scorer is to aggregate the data. That it can be used to loop over the data in an elegant way is more of nice "side-effect".

I think the best way at the moment is to go by index.

I would suggest to maybe merge the dataset index with the output somehow:

```
dataset = Dataset()
scorer = Scorer()

agg_res, single_res = scorer(dataset)

combined_single_res = {d.group: r for (d, r) in zip(dataset, single_res)}
```

However, I think there is room in tpcp to implement a function that is more focused on the "iterating" side of it. So like `cross_validate` (which provides the group labels in the output), just without the cross-validation part.

Any suggestions on how such an output could look like?

One way would be to have it look like one row of the cross_validate output (see e.g. here: https://tpcp.readthedocs.io/en/latest/auto_examples/validation/_01_cross_validation.html#sphx-glr-auto-examples-validation-01-cross-validation-py)

**Comment by AKuederle** [comment]
Additional note to this: It is sometimes easier in larger datastructures to not store the Dataset Objects themself, but just the groups (`dataset.groups`/`datapoint.group`).

To get back a dataset object from the groups, you should be able to use `Dataset().get_subset(groups=groups)` (or in case of a single group `Dataset().get_subset(groups=[group])`)

**Comment by felixkluge** [comment]
If there are multiple scores (`score_1`, `score_2`, etc.), the specific score would need to be referenced while zipping, correct? Otherwise, the `score_1` has the index of the first datapoint, the `score_2` the index of the second, etc...

```
combined_single_res_score_1 = {d: r for (d, r) in zip(dataset.groups, single_res['score_1'])}
```

would then create a dict with a datapoint (?) as key, and the respective `score_1` as value.

How can I then convert this dictionary to a DataFrame with the original indizes of the dataset (potentially set as MultiIndex) and one column indicating `score_1`? More specifically, how do I convert the keys to "something" that can be merged with the values into a DataFrame?

**Comment by AKuederle** [comment]
You should be able to join by index relativly easily.

```python
dataset_index = Dataset().index

combined = dataset.index.assign(**single_res) # I think this should just work, if you return multiple scores
```

**Comment by felixkluge** [comment]
Thanks, that works!

**Comment by AKuederle** [comment]
Will close for now :)
